In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df= pd.read_csv('/content/Variables.csv',sep=';')

In [5]:
df.describe()

,ano,mes,id,tamano,sexo,grupo,div,ho_t_1,c_t_1,ht_t_1,ho,c,ht
count,31644.0,31644.0,31644.000000,31644.000000,31644.000000,31644.00000,31644.000000,1.652100e+04,1.652100e+04,1.652100e+04,1.654700e+04,1.654700e+04,1.654700e+04
mean,2023.0,7.0,957.583618,2.510239,1.500000,5.00000,2.806030,1.490354e+04,1.437646e+08,1.540128e+04,1.486716e+04,1.445303e+08,1.542179e+04
std,0.0,0.0,549.379373,0.781378,0.500008,2.58203,3.248299,4.953672e+04,4.829497e+08,5.109663e+04,4.943780e+04,4.860388e+08,5.127724e+04
min,2023.0,7.0,1.000000,1.000000,1.000000,1.00000,1.000000,2.000000e+00,1.416100e+04,2.000000e+00,2.000000e+00,1.324200e+04,2.000000e+00
25%,2023.0,7.0,481.000000,2.000000,1.000000,3.00000,1.000000,5.790000e+02,5.086820e+06,5.810000e+02,5.740000e+02,5.121074e+06,5.800000e+02
50%,2023.0,7.0,968.500000,3.000000,1.500000,5.00000,2.000000,2.174000e+03,2.138843e+07,2.246000e+03,2.169000e+03,2.147767e+07,2.238000e+03
75%,2023.0,7.0,1430.000000,3.000000,2.000000,7.00000,3.000000,9.475000e+03,8.692053e+07,9.815000e+03,9.460000e+03,8.669455e+07,9.774000e+03
max,2023.0,7.0,1911.000000,3.000000,2.000000,9.00000,21.000000,2.048760e+06,1.110655e+10,2.049033e+06,2.041389e+06,1.130031e+10,2.041701e+06

In [6]:
df = df.drop(['ho_t_1','c_t_1', 'ht_t_1', 'ro', 'ho', 'c', 'ht'], axis=1)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31644 entries, 0 to 31643
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ano        31644 non-null  int64
 1   mes        31644 non-null  int64
 2   id         31644 non-null  int64
 3   tamano     31644 non-null  int64
 4   categoria  31644 non-null  object
 5   sexo       31644 non-null  object
 6   grupo      31644 non-null  object
 7   div        31644 non-null  int64
 8   ro_t_1     16521 non-null  object
dtypes: int64(5), object(4)
memory usage: 2.2+ MB

In [12]:
# Suponiendo que tienes un DataFrame llamado 'df'
df['categoria'] = df['categoria'].astype(str)
df['sexo'] = df['sexo'].astype(str)
df['grupo'] = df['grupo'].astype(str)

In [16]:
# Convertir la columna 'ro_t_1' a números (float)
df['ro_t_1'] = pd.to_numeric(df['ro_t_1'], errors='coerce')

# Verificar si hay valores nulos después de la conversión
print(df['ro_t_1'].isnull().sum())  # Para contar valores nulos en la columna

15143

In [18]:
# Agrupar por Categoria, Sexo y Grupo y calcular la media de la remuneración
df = df.groupby(['categoria', 'sexo', 'grupo'])['ro_t_1'].mean().reset_index()
print(df)

    categoria sexo grupo        ro_t_1
0           B    1     1  7.119866e+07
1           B    1     2  2.703667e+08
2           B    1     3  4.891938e+07
3           B    1     4  1.583538e+07
4           B    1     5  2.421580e+06
..        ...  ...   ...           ...
301         R    2     5  1.902420e+07
302         R    2     6  1.345021e+07
303         R    2     7  7.000993e+06
304         R    2     8  5.778529e+06
305         R    2     9  1.114965e+07

[306 rows x 4 columns]

In [20]:
# Estadísticos descriptivos por Categoria, Sexo y Grupo para la remuneración
df2= df.groupby(['categoria', 'sexo', 'grupo'])['ro_t_1'].describe()
print(df2)

                      count          mean  std           min           25%  \
categoria sexo grupo
B         1    1        1.0  7.119866e+07  NaN  7.119866e+07  7.119866e+07
               2        1.0  2.703667e+08  NaN  2.703667e+08  2.703667e+08
               3        1.0  4.891938e+07  NaN  4.891938e+07  4.891938e+07
               4        1.0  1.583538e+07  NaN  1.583538e+07  1.583538e+07
               5        1.0  2.421580e+06  NaN  2.421580e+06  2.421580e+06
...                     ...           ...  ...           ...           ...
R         2    5        1.0  1.902420e+07  NaN  1.902420e+07  1.902420e+07
               6        1.0  1.345021e+07  NaN  1.345021e+07  1.345021e+07
               7        1.0  7.000993e+06  NaN  7.000993e+06  7.000993e+06
               8        1.0  5.778529e+06  NaN  5.778529e+06  5.778529e+06
               9        1.0  1.114965e+07  NaN  1.114965e+07  1.114965e+07

                               50%           75%           max
categoria sexo grupo
B         1    1      7.119866e+07  7.119866e+07  7.119866e+07
               2      2.703667e+08  2.703667e+08  2.703667e+08
               3      4.891938e+07  4.891938e+07  4.891938e+07
               4      1.583538e+07  1.583538e+07  1.583538e+07
               5      2.421580e+06  2.421580e+06  2.421580e+06
...                            ...           ...           ...
R         2    5      1.902420e+07  1.902420e+07  1.902420e+07
               6      1.345021e+07  1.345021e+07  1.345021e+07
               7      7.000993e+06  7.000993e+06  7.000993e+06
               8      5.778529e+06  5.778529e+06  5.778529e+06
               9      1.114965e+07  1.114965e+07  1.114965e+07

[306 rows x 8 columns]